version: '3'
services:

  jupyter:
    build:
      context: .
    ports:
       - "8998:8998"
       - "5006:5006"
    volumes:
       - ../:/mnt
    entrypoint: bash -c "curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs && jupyter labextension install @jupyterlab/toc && jupyter labextension install @aquirdturtle/collapsible_headings && pip install nb_black && cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root --port=8998 --no-browser && /bin/bash" 
    stdin_open: true
    container_name: "panel_dashboard_jupyter_${USER}"
    tty: true
    env_file:
      - ../.env 

  mlflow:
    build:
      context: .
    ports:
      - "127.0.0.1::5000"
    volumes:
       - ../:/mnt
    entrypoint: bash -c "mlflow server -h 0.0.0.0 --backend-store-uri ${MLFLOW_TRACKING_URI} --default-artifact-root ${MLFLOW_ARTIFACT_LOCATION:-'None'} -p 5000 && /bin/bash" 
    stdin_open: true
    container_name: "panel_dashboard_mlflow_${USER}"
    tty: true
    env_file:
      - ../.env 

  bash:
    build:
      context: .
    volumes:
       - ../:/mnt
    entrypoint: "/bin/bash" 
    stdin_open: true
    container_name: "panel_dashboard_bash_${USER}"
    tty: true
    env_file:
      - ../.env 
